import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdir, mkdtemp, readFile, writeFile, rm } from 'node:fs/promises';
import { createServer } from '../server/index.mjs';
import { createWorker } from '../server/ai/worker.mjs';
import { createStore } from '../server/ai/store.mjs';
import { ff, inspect } from '../server/ai/render.mjs';

test('real upload → Whisper → preview → approved 1080p export; Gemini semantic contract is mocked', { timeout: 240000 }, async t => {
  const temporaryRoot = path.resolve('.scena/test-ai');
  await mkdir(temporaryRoot, { recursive: true });
  const dataDir = await mkdtemp(path.join(temporaryRoot, 'workflow-'));
  const envKeys = ['OPENROUTER_API_KEY', 'OPENAI_API_KEY', 'GEMINI_API_KEY', 'SUPABASE_URL', 'SUPABASE_SECRET_KEY', 'S3_ENDPOINT', 'S3_BUCKET', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY', 'HF_HUB_OFFLINE', 'TRANSFORMERS_OFFLINE'];
  const previous = Object.fromEntries(envKeys.map(key => [key, process.env[key]]));
  for (const key of envKeys) delete process.env[key];
  process.env.HF_HUB_OFFLINE = '1'; process.env.TRANSFORMERS_OFFLINE = '1';
  let server, worker, store, semanticCalls = 0, editCalls = 0;
  try {
    server = await createServer({ dataDir, seed: false });
    await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
    const base = `http://127.0.0.1:${server.address().port}`;
    const api = async (route, { body, ...options } = {}) => {
      const response = await fetch(base + route, { ...options, ...(body === undefined ? {} : { body: Buffer.isBuffer(body) ? body : JSON.stringify(body) }) });
      const data = await response.json();
      return { response, data };
    };
    const input = await readFile('public/videos/platform-example-5958.mp4');
    assert.equal((await api('/api/video/config')).data.aiReady, false);
    const created = await api('/api/video/projects', { method: 'POST', body: { name: 'workflow.mp4', size: input.length } });
    assert.equal(created.response.status, 201);
    const id = created.data.project.id, route = `/api/video/projects/${id}`;
    assert.equal((await api(`${route}/analyze`, { method: 'POST' })).response.status, 503, 'missing Gemini key is an explicit unavailable service');
    assert.equal((await api(`${route}/complete`, { method: 'POST' })).response.status, 409);
    assert.equal((await api(`${route}/upload`, { method: 'PUT', body: input.subarray(0, 10), headers: { 'Upload-Offset': '1' } })).response.status, 409);
    const chunkSize = 2 * 1024 ** 2;
    for (let offset = 0; offset < input.length; offset += chunkSize) {
      const uploaded = await api(`${route}/upload`, { method: 'PUT', body: input.subarray(offset, Math.min(input.length, offset + chunkSize)), headers: { 'Upload-Offset': String(offset) } });
      assert.equal(uploaded.response.status, 200, JSON.stringify(uploaded.data));
      assert.equal(uploaded.data.offset, Math.min(input.length, offset + chunkSize));
    }
    const completed = await api(`${route}/complete`, { method: 'POST' });
    assert.equal(completed.response.status, 202, JSON.stringify(completed.data));
    assert.equal((await api(`${route}/complete`, { method: 'POST' })).response.status, 409);
    const provider = {
      async analyzeVideo({ filePath, duration, transcript, scenes }) {
        semanticCalls++;
        assert.equal((await inspect(filePath)).codec, 'h264');
        assert.ok(duration > 20 && duration < 30);
        assert.ok(Array.isArray(transcript), 'transcript comes from real offline Whisper');
        assert.ok(scenes.length > 0, 'scenes come from real PySceneDetect');
        return { model: 'test-semantic-provider', candidates: [{ start: 1, end: 6, duration: 5, title: 'Тестовый момент', description: 'Фрагмент для проверки обработки', hook: 'Начало фрагмента', category: 'test', score: 90, reason: 'Предсказуемый результат тестового провайдера', recommended_format: '9:16', recommended_editing: ['Сохранить речь'] }] };
      },
      async interpretEditRequest({ request, settings }) {
        editCalls++;
        assert.equal(request, 'Сделай квадратным и отключи звук');
        assert.equal(settings.format, '9:16');
        return { format: '1:1', muted: true };
      },
    };
    worker = await createWorker({ dataDir, env: {}, provider });
    const runJob = async jobId => {
      assert.equal(await worker.once(), true);
      const result = await api(`/api/video/jobs/${jobId}`);
      assert.equal(result.data.job.status, 'done', JSON.stringify(result.data.job));
    };
    await runJob(completed.data.job.id);
    let project = (await api(route)).data.project;
    assert.equal(project.status, 'ANALYZING');
    await runJob(project.jobId);
    project = (await api(route)).data.project;
    assert.equal(project.status, 'READY');
    assert.equal(semanticCalls, 1);
    assert.equal(project.analysisModel, 'test-semantic-provider');
    store = await createStore({ dataDir: path.join(dataDir, 'ai'), env: {} });
    const analyzed = await store.getProject('local', id);
    assert.ok(analyzed.analysis.tracking.length > 0);
    assert.ok(Array.isArray(analyzed.analysis.segments));
    assert.equal(typeof analyzed.analysis.language, 'string');
    assert.equal(project.analysis, undefined, 'polling does not transfer the full film transcript');
    assert.equal(project.candidates.length, 1);
    assert.equal((await api(`${route}/analyze`, { method: 'POST' })).data.cached, true);
    assert.equal(await worker.once(), false, 'cached analysis must not enqueue a duplicate model request');
    const candidateUrl = `${route}/files/${project.candidates[0].id}`;
    const ranged = await fetch(base + candidateUrl, { headers: { Range: 'bytes=0-31' } });
    assert.equal(ranged.status, 206);
    assert.equal((await ranged.arrayBuffer()).byteLength, 32);
    assert.equal((await fetch(base + candidateUrl, { headers: { Range: 'bytes=999999999999-' } })).status, 416);
    assert.equal((await fetch(base + candidateUrl, { headers: { Range: 'bytes=abc' } })).status, 416);
    assert.equal(await store.getProject('another-owner', id), null);
    assert.equal(await store.getJob('another-owner', project.jobId), null);
    const preview = await api(`${route}/preview`, { method: 'POST', body: { sceneId: project.candidates[0].id } });
    assert.equal(preview.response.status, 202, JSON.stringify(preview.data));
    await runJob(preview.data.job.id);
    project = (await api(route)).data.project;
    assert.equal(project.status, 'AWAITING_APPROVAL');
    assert.equal(project.versions.length, 1);
    const versionId = project.currentVersion;
    assert.equal((await api(`${route}/advertisement?filename=before-approval.png`, { method: 'POST', body: Buffer.from('unapproved asset') })).response.status, 409, 'advertisement upload requires an approved clip');
    assert.equal((await api(`${route}/export`, { method: 'POST', body: {} })).response.status, 409);
    const revision = await api(`${route}/revise`, { method: 'POST', body: { request: 'Сделай квадратным и отключи звук' } });
    assert.equal(revision.response.status, 202, JSON.stringify(revision.data));
    await runJob(revision.data.job.id);
    project = (await api(route)).data.project;
    assert.equal(editCalls, 1);
    assert.equal(project.versions.length, 2);
    assert.equal(project.settings.format, '1:1');
    assert.equal(project.settings.muted, true);
    const revisionFile = path.join(dataDir, 'revision.mp4');
    await writeFile(revisionFile, Buffer.from(await (await fetch(base + `${route}/files/${project.currentVersion}`)).arrayBuffer()));
    const revisionMetadata = await inspect(revisionFile);
    assert.deepEqual([revisionMetadata.width, revisionMetadata.height], [540, 540]);
    assert.equal(revisionMetadata.hasAudio, false);
    project = (await api(`${route}/restore`, { method: 'POST', body: { versionId } })).data.project;
    assert.equal(project.settings.format, '9:16');
    assert.equal(project.settings.muted, false);
    assert.equal((await api(`${route}/approve`, { method: 'POST' })).data.project.status, 'APPROVED');
    const approvedSettings = structuredClone(project.settings);
    const banner = path.join(dataDir, 'banner.png');
    await ff(['-f', 'lavfi', '-i', 'color=c=0xff00ff:s=320x80', '-frames:v', '1', banner]);
    const advertisement = await api(`${route}/advertisement?filename=banner.png`, { method: 'POST', body: await readFile(banner) });
    assert.equal(advertisement.response.status, 202, JSON.stringify(advertisement.data));
    await runJob(advertisement.data.job.id);
    project = (await api(route)).data.project;
    assert.equal(project.status, 'ADDING_AD');
    assert.ok(project.ad.fileId);
    assert.equal(project.files[project.ad.fileId].mime, 'image/png');
    const updatedAd = await api(`${route}/advertisement`, { method: 'PUT', body: { position: 'top', width: 40, start: 0, duration: 2, opacity: 1 } });
    assert.equal(updatedAd.response.status, 200, JSON.stringify(updatedAd.data));
    assert.equal((await api(`${route}/export`, { method: 'POST', body: {} })).response.status, 409, 'export with an advertisement requires its preview');
    const adPreview = await api(`${route}/ad-preview`, { method: 'POST', body: {} });
    assert.equal(adPreview.response.status, 202, JSON.stringify(adPreview.data));
    await runJob(adPreview.data.job.id);
    project = (await api(route)).data.project;
    assert.equal(project.status, 'ADDING_AD');
    assert.ok(project.adPreview);
    assert.equal(project.currentVersion, versionId);
    assert.equal(project.versions.length, 2, 'ad preview does not replace approved edit versions');
    const exported = await api(`${route}/export`, { method: 'POST', body: { settings: { start: 0, end: 10, format: '1:1', muted: true } } });
    assert.equal(exported.response.status, 202, JSON.stringify(exported.data));
    await runJob(exported.data.job.id);
    project = (await api(route)).data.project;
    assert.equal(project.status, 'COMPLETED');
    assert.deepEqual(project.settings, approvedSettings, 'export must retain the approved version and ignore unapproved request settings');
    const download = await fetch(base + `${route}/files/${project.finalFile}`);
    assert.equal(download.status, 200);
    assert.match(download.headers.get('content-disposition'), /attachment/);
    const output = path.join(dataDir, 'verified-export.mp4');
    await writeFile(output, Buffer.from(await download.arrayBuffer()));
    const metadata = await inspect(output);
    assert.deepEqual([metadata.width, metadata.height], [1080, 1920]);
    assert.equal(metadata.codec, 'h264');
    assert.ok(metadata.duration >= 4.9 && metadata.duration <= 5.2);
    assert.ok(metadata.duration <= 120);
    const legacy = await store.getProject('local',id);
    const earlierExport = legacy.finalFile;
    delete legacy.exports;
    await store.saveProject('local',legacy);
    const repeated = await api(`${route}/export`,{method:'POST'});
    await runJob(repeated.data.job.id);
    const history = (await api(route)).data.project;
    assert.equal(history.exports.length,2);
    assert.equal(history.exports[0].id,earlierExport,'exporting a legacy project must preserve its previous downloadable clip');
    assert.equal(history.exports[1].id,history.finalFile);
    const restored = await api(`${route}/restore`, { method: 'POST', body: { versionId } });
    assert.equal(restored.data.project.status, 'AWAITING_APPROVAL');
    assert.equal(restored.data.project.currentVersion, versionId);
    assert.equal(await worker.once(), false);
    t.diagnostic('FFmpeg, ffprobe, PySceneDetect, OpenCV and cached Whisper ran locally; only Gemini semantic selection was replaced by an explicit test provider. No external services were called.');
  } finally {
    await worker?.close(); await store?.close();
    if (server) await new Promise(resolve => server.close(resolve));
    for (const [key, value] of Object.entries(previous)) { if (value === undefined) delete process.env[key]; else process.env[key] = value; }
    const resolved = path.resolve(dataDir);
    assert.ok(resolved.startsWith(`${temporaryRoot}${path.sep}`), 'cleanup stays inside the dedicated test directory');
    await rm(resolved, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
  }
});
